openapi: 3.0.1
info:
  title: Data Read - Employee - External
  description: ''
  version: '1.0'
servers:
  - url: https://ausazinnbwgapim01.azure-api.net/external/dtrd-emp-ext/v1
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]