openapi: 3.0.1
info:
  title: System Read - SuccessFactors - Employee Central - Internal
  description: ''
  version: '1.0'
servers:
  - url: https://ausazinnbwgapim01.azure-api.net/internal/sysrd-sfac-employeeCentral-int/v1
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]